### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by brentjanderson** [pcnsuite/pcnspec#13]
- Is there a range to value_specific? It says any integer, but that means -10000 could be valid.
- Same question for value_generic?
- Are IDs unique across the internal document? Say, can a step and a domain share the same ID? I'm guessing that's the case, but I would like to know on this one.

**Comment by mjswensen** [comment]
Sorry I didn't see this earlier, @brentjanderson . I know it's not as relevant now since you have finished your project (awesome work, by the way).
1. No, there are no bounds to `value_specific`.
2. Same for `value_generic`.
3. We discussed this with our team and landed on making them unique to the document. So no, a step and a domain shouldn't share an ID. I'll put an issue on your [linter](https://github.com/brentjanderson/pcnlint) to make sure we enforce that.
